spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: redis-operate
  redis:
    # Redis服务器地址
    host: ${rookie-redis.redis.host}
    # Redis服务器端口号
    port: ${rookie-redis.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${rookie-redis.redis.password}
